export const surahMetadata = [
    { number: 1, name: "سُورَةُ ٱلْفَاتِحَةِ", englishName: "Al-Fatihah", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan", aliases: ["Fatiha"] },
    { number: 2, name: "سُورَةُ البَقَرَةِ", englishName: "Al-Baqarah", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan", aliases: ["Baqarah"] },
    { number: 3, name: "سُورَةُ آلِ عِمْرَانَ", englishName: "Ali 'Imran", englishNameTranslation: "Family of Imran", numberOfAyahs: 200, revelationType: "Medinan", aliases: ["Al Imran", "Imran"] },
    { number: 4, name: "سُورَةُ النِّسَاءِ", englishName: "An-Nisa", englishNameTranslation: "The Women", numberOfAyahs: 176, revelationType: "Medinan", aliases: ["Nisa"] },
    { number: 5, name: "سُورَةُ الْمَائِدَةِ", englishName: "Al-Ma'idah", englishNameTranslation: "The Table Spread", numberOfAyahs: 120, revelationType: "Medinan", aliases: ["Maidah"] },
    { number: 6, name: "سُورَةُ الْأَنْعَامِ", englishName: "Al-An'am", englishNameTranslation: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan", aliases: ["Anam"] },
    { number: 7, name: "سُورَةُ الْأَعْرَافِ", englishName: "Al-A'raf", englishNameTranslation: "The Heights", numberOfAyahs: 206, revelationType: "Meccan", aliases: ["Araf"] },
    { number: 8, name: "سُورَةُ الْأَنْفَالِ", englishName: "Al-Anfal", englishNameTranslation: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan", aliases: ["Anfal"] },
    { number: 9, name: "سُورَةُ التَّوْبَةِ", englishName: "At-Tawbah", englishNameTranslation: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan", aliases: ["Tawbah"] },
    { number: 10, name: "سُورَةُ يُونُسَ", englishName: "Yunus", englishNameTranslation: "Jonah", numberOfAyahs: 109, revelationType: "Meccan", aliases: ["Younus"] },
    { number: 11, name: "سُورَةُ هُودٍ", englishName: "Hud", englishNameTranslation: "Hud", numberOfAyahs: 123, revelationType: "Meccan", aliases: [] },
    { number: 12, name: "سُورَةُ يُوسُفَ", englishName: "Yusuf", englishNameTranslation: "Joseph", numberOfAyahs: 111, revelationType: "Meccan", aliases: ["Yousuf"] },
    { number: 13, name: "سُورَةُ الرَّعْدِ", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", numberOfAyahs: 43, revelationType: "Medinan", aliases: ["Rad"] },
    { number: 14, name: "سُورَةُ إِبْرَاهِيمَ", englishName: "Ibrahim", englishNameTranslation: "Abraham", numberOfAyahs: 52, revelationType: "Meccan", aliases: [] },
    { number: 15, name: "سُورَةُ الْحِجْرِ", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan", aliases: ["Hijr"] },
    { number: 16, name: "سُورَةُ النَّحْلِ", englishName: "An-Nahl", englishNameTranslation: "The Bee", numberOfAyahs: 128, revelationType: "Meccan", aliases: ["Nahl"] },
    { number: 17, name: "سُورَةُ الْإِسْرَاءِ", englishName: "Al-Isra", englishNameTranslation: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan", aliases: ["Isra"] },
    { number: 18, name: "سُورَةُ الْكَهْفِ", englishName: "Al-Kahf", englishNameTranslation: "The Cave", numberOfAyahs: 110, revelationType: "Meccan", aliases: ["Kahf"] },
    { number: 19, name: "سُورَةُ مَرْيَمَ", englishName: "Maryam", englishNameTranslation: "Mary", numberOfAyahs: 98, revelationType: "Meccan", aliases: [] },
    { number: 20, name: "سُورَةُ طه", englishName: "Taha", englishNameTranslation: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan", aliases: ["Ta Ha"] },
    { number: 21, name: "سُورَةُ الْأَنْبِيَاءِ", englishName: "Al-Anbya", englishNameTranslation: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan", aliases: ["Anbiya"] },
    { number: 22, name: "سُورَةُ الْحَجِّ", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan", aliases: ["Hajj"] },
    { number: 23, name: "سُورَةُ الْمُؤْمِنُونَ", englishName: "Al-Mu'minun", englishNameTranslation: "The Believers", numberOfAyahs: 118, revelationType: "Meccan", aliases: ["Muminun"] },
    { number: 24, name: "سُورَةُ النُّورِ", englishName: "An-Nur", englishNameTranslation: "The Light", numberOfAyahs: 64, revelationType: "Medinan", aliases: ["Nur"] },
    { number: 25, name: "سُورَةُ الْفُرْقَانِ", englishName: "Al-Furqan", englishNameTranslation: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan", aliases: ["Furqan"] },
    { number: 26, name: "سُورَةُ الشُّعَرَاءِ", englishName: "Ash-Shu'ara", englishNameTranslation: "The Poets", numberOfAyahs: 227, revelationType: "Meccan", aliases: ["Shuara"] },
    { number: 27, name: "سُورَةُ النَّمْلِ", englishName: "An-Naml", englishNameTranslation: "The Ant", numberOfAyahs: 93, revelationType: "Meccan", aliases: ["Naml"] },
    { number: 28, name: "سُورَةُ الْقَصَصِ", englishName: "Al-Qasas", englishNameTranslation: "The Stories", numberOfAyahs: 88, revelationType: "Meccan", aliases: ["Qasas"] },
    { number: 29, name: "سُورَةُ الْعَنْكَبُوتِ", englishName: "Al-'Ankabut", englishNameTranslation: "The Spider", numberOfAyahs: 69, revelationType: "Meccan", aliases: ["Ankabut"] },
    { number: 30, name: "سُورَةُ الرُّومِ", englishName: "Ar-Rum", englishNameTranslation: "The Romans", numberOfAyahs: 60, revelationType: "Meccan", aliases: ["Rum"] },
    { number: 31, name: "سُورَةُ لُقْمَانَ", englishName: "Luqman", englishNameTranslation: "Luqman", numberOfAyahs: 34, revelationType: "Meccan", aliases: [] },
    { number: 32, name: "سُورَةُ السَّجْدَةِ", englishName: "As-Sajdah", englishNameTranslation: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan", aliases: ["Sajdah"] },
    { number: 33, name: "سُورَةُ الْأَحْزَابِ", englishName: "Al-Ahzab", englishNameTranslation: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan", aliases: ["Ahzab"] },
    { number: 34, name: "سُورَةُ سَبَإٍ", englishName: "Saba", englishNameTranslation: "Sheba", numberOfAyahs: 54, revelationType: "Meccan", aliases: [] },
    { number: 35, name: "سُورَةُ فَاطِرٍ", englishName: "Fatir", englishNameTranslation: "Originator", numberOfAyahs: 45, revelationType: "Meccan", aliases: [] },
    { number: 36, name: "سُورَةُ يس", englishName: "Ya-Sin", englishNameTranslation: "Ya Sin", numberOfAyahs: 83, revelationType: "Meccan", aliases: ["Yasin", "Yaseen"] },
    { number: 37, name: "سُورَةُ الصَّافَّاتِ", englishName: "As-Saffat", englishNameTranslation: "Those who set the Ranks", numberOfAyahs: 182, revelationType: "Meccan", aliases: ["Saffat"] },
    { number: 38, name: "سُورَةُ ص", englishName: "Sad", englishNameTranslation: "The Letter 'Saad'", numberOfAyahs: 88, revelationType: "Meccan", aliases: ["Saad"] },
    { number: 39, name: "سُورَةُ الزُّمَرِ", englishName: "Az-Zumar", englishNameTranslation: "The Troops", numberOfAyahs: 75, revelationType: "Meccan", aliases: ["Zumar"] },
    { number: 40, name: "سُورَةُ غَافِرٍ", englishName: "Ghafir", englishNameTranslation: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan", aliases: [] },
    { number: 41, name: "سُورَةُ فُصِّلَتْ", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", numberOfAyahs: 54, revelationType: "Meccan", aliases: ["Ha Mim Sajdah"] },
    { number: 42, name: "سُورَةُ الشُّورَىٰ", englishName: "Ash-Shura", englishNameTranslation: "The Consultation", numberOfAyahs: 53, revelationType: "Meccan", aliases: ["Shura"] },
    { number: 43, name: "سُورَةُ الزُّخْرُفِ", englishName: "Az-Zukhruf", englishNameTranslation: "The Ornaments of Gold", numberOfAyahs: 89, revelationType: "Meccan", aliases: ["Zukhruf"] },
    { number: 44, name: "سُورَةُ الدُّخَانِ", englishName: "Ad-Dukhan", englishNameTranslation: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan", aliases: ["Dukhan"] },
    { number: 45, name: "سُورَةُ الْجَاثِيَةِ", englishName: "Al-Jathiyah", englishNameTranslation: "The Crouching", numberOfAyahs: 37, revelationType: "Meccan", aliases: ["Jathiyah"] },
    { number: 46, name: "سُورَةُ الْأَحْقَافِ", englishName: "Al-Ahqaf", englishNameTranslation: "The Wind-Curved Sandhills", numberOfAyahs: 35, revelationType: "Meccan", aliases: ["Ahqaf"] },
    { number: 47, name: "سُورَةُ مُحَمَّدٍ", englishName: "Muhammad", englishNameTranslation: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan", aliases: [] },
    { number: 48, name: "سُورَةُ الْفَتْحِ", englishName: "Al-Fath", englishNameTranslation: "The Victory", numberOfAyahs: 29, revelationType: "Medinan", aliases: ["Fath"] },
    { number: 49, name: "سُورَةُ الْحُجُرَاتِ", englishName: "Al-Hujurat", englishNameTranslation: "The Rooms", numberOfAyahs: 18, revelationType: "Medinan", aliases: ["Hujurat"] },
    { number: 50, name: "سُورَةُ ق", englishName: "Qaf", englishNameTranslation: "The Letter 'Qaf'", numberOfAyahs: 45, revelationType: "Meccan", aliases: [] },
    { number: 51, name: "سُورَةُ الذَّارِيَاتِ", englishName: "Adh-Dhariyat", englishNameTranslation: "The Winnowing Winds", numberOfAyahs: 60, revelationType: "Meccan", aliases: ["Dhariyat"] },
    { number: 52, name: "سُورَةُ الطُّورِ", englishName: "At-Tur", englishNameTranslation: "The Mount", numberOfAyahs: 49, revelationType: "Meccan", aliases: ["Tur"] },
    { number: 53, name: "سُورَةُ النَّجْمِ", englishName: "An-Najm", englishNameTranslation: "The Star", numberOfAyahs: 62, revelationType: "Meccan", aliases: ["Najm"] },
    { number: 54, name: "سُورَةُ الْقَمَرِ", englishName: "Al-Qamar", englishNameTranslation: "The Moon", numberOfAyahs: 55, revelationType: "Meccan", aliases: ["Qamar"] },
    { number: 55, name: "سُورَةُ الرَّحْمَٰنِ", englishName: "Ar-Rahman", englishNameTranslation: "The Most Merciful", numberOfAyahs: 78, revelationType: "Medinan", aliases: ["Rahman"] },
    { number: 56, name: "سُورَةُ الْوَاقِعَةِ", englishName: "Al-Waqi'ah", englishNameTranslation: "The Inevitable", numberOfAyahs: 96, revelationType: "Meccan", aliases: ["Waqiah"] },
    { number: 57, name: "سُورَةُ الْحَدِيدِ", englishName: "Al-Hadid", englishNameTranslation: "The Iron", numberOfAyahs: 29, revelationType: "Medinan", aliases: ["Hadid"] },
    { number: 58, name: "سُورَةُ الْمُجَادِلَةِ", englishName: "Al-Mujadila", englishNameTranslation: "The Pleading Woman", numberOfAyahs: 22, revelationType: "Medinan", aliases: ["Mujadila"] },
    { number: 59, name: "سُورَةُ الْحَشْرِ", englishName: "Al-Hashr", englishNameTranslation: "The Exile", numberOfAyahs: 24, revelationType: "Medinan", aliases: ["Hashr"] },
    { number: 60, name: "سُورَةُ الْمُمْتَحَنَةِ", englishName: "Al-Mumtahanah", englishNameTranslation: "She that is to be examined", numberOfAyahs: 13, revelationType: "Medinan", aliases: ["Mumtahanah"] },
    { number: 61, name: "سُورَةُ الصَّفِّ", englishName: "As-Saf", englishNameTranslation: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan", aliases: ["Saf"] },
    { number: 62, name: "سُورَةُ الْجُمُعَةِ", englishName: "Al-Jumu'ah", englishNameTranslation: "The Congregation, Friday", numberOfAyahs: 11, revelationType: "Medinan", aliases: ["Jummah", "Jumuah"] },
    { number: 63, name: "سُورَةُ الْمُنَافِقُونَ", englishName: "Al-Munafiqun", englishNameTranslation: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan", aliases: ["Munafiqun"] },
    { number: 64, name: "سُورَةُ التَّغَابُنِ", englishName: "At-Taghabun", englishNameTranslation: "The Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan", aliases: ["Taghabun"] },
    { number: 65, name: "سُورَةُ الطَّلَاقِ", englishName: "At-Talaq", englishNameTranslation: "The Divorce", numberOfAyahs: 12, revelationType: "Medinan", aliases: ["Talaq"] },
    { number: 66, name: "سُورَةُ التَّحْرِيمِ", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", numberOfAyahs: 12, revelationType: "Medinan", aliases: ["Tahrim"] },
    { number: 67, name: "سُورَةُ الْمُلْكِ", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan", aliases: ["Mulk"] },
    { number: 68, name: "سُورَةُ الْقَلَمِ", englishName: "Al-Qalam", englishNameTranslation: "The Pen", numberOfAyahs: 52, revelationType: "Meccan", aliases: ["Qalam"] },
    { number: 69, name: "سُورَةُ الْحَاقَّةِ", englishName: "Al-Haqqah", englishNameTranslation: "The Reality", numberOfAyahs: 52, revelationType: "Meccan", aliases: ["Haqqah"] },
    { number: 70, name: "سُورَةُ الْمَعَارِجِ", englishName: "Al-Ma'arij", englishNameTranslation: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan", aliases: ["Maarij"] },
    { number: 71, name: "سُورَةُ نُوحٍ", englishName: "Nuh", englishNameTranslation: "Noah", numberOfAyahs: 28, revelationType: "Meccan", aliases: [] },
    { number: 72, name: "سُورَةُ الْجِنِّ", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan", aliases: ["Jinn"] },
    { number: 73, name: "سُورَةُ الْمُزَّمِّلِ", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan", aliases: ["Muzzammil"] },
    { number: 74, name: "سُورَةُ الْمُدَّثِّرِ", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan", aliases: ["Muddaththir"] },
    { number: 75, name: "سُورَةُ الْقِيَامَةِ", englishName: "Al-Qiyamah", englishNameTranslation: "The Resurrection", numberOfAyahs: 40, revelationType: "Meccan", aliases: ["Qiyamah"] },
    { number: 76, name: "سُورَةُ الْإِنْسَانِ", englishName: "Al-Insan", englishNameTranslation: "Man", numberOfAyahs: 31, revelationType: "Medinan", aliases: ["Insan"] },
    { number: 77, name: "سُورَةُ الْمُرْسَلَاتِ", englishName: "Al-Mursalat", englishNameTranslation: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan", aliases: ["Mursalat"] },
    { number: 78, name: "سُورَةُ النَّبَإِ", englishName: "An-Naba", englishNameTranslation: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan", aliases: ["Naba"] },
    { number: 79, name: "سُورَةُ النَّازِعَاتِ", englishName: "An-Nazi'at", englishNameTranslation: "Those who drag forth", numberOfAyahs: 46, revelationType: "Meccan", aliases: ["Naziat"] },
    { number: 80, name: "سُورَةُ عَبَسَ", englishName: "'Abasa", englishNameTranslation: "He Frowned", numberOfAyahs: 42, revelationType: "Meccan", aliases: ["Abasa"] },
    { number: 81, name: "سُورَةُ التَّكْوِيرِ", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan", aliases: ["Takwir"] },
    { number: 82, name: "سُورَةُ الِانْفِطَارِ", englishName: "Al-Infitar", englishNameTranslation: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan", aliases: ["Infitar"] },
    { number: 83, name: "سُورَةُ الْمُطَفِّفِينَ", englishName: "Al-Mutaffifin", englishNameTranslation: "The Defrauding", numberOfAyahs: 36, revelationType: "Meccan", aliases: ["Mutaffifin"] },
    { number: 84, name: "سُورَةُ الِانْشِقَاقِ", englishName: "Al-Inshiqaq", englishNameTranslation: "The Sundering", numberOfAyahs: 25, revelationType: "Meccan", aliases: ["Inshiqaq"] },
    { number: 85, name: "سُورَةُ الْبُرُوجِ", englishName: "Al-Buruj", englishNameTranslation: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan", aliases: ["Buruj"] },
    { number: 86, name: "سُورَةُ الطَّارِقِ", englishName: "At-Tariq", englishNameTranslation: "The Nightcommer", numberOfAyahs: 17, revelationType: "Meccan", aliases: ["Tariq"] },
    { number: 87, name: "سُورَةُ الْأَعْلَىٰ", englishName: "Al-A'la", englishNameTranslation: "The Most High", numberOfAyahs: 19, revelationType: "Meccan", aliases: ["Ala"] },
    { number: 88, name: "سُورَةُ الْغَاشِيَةِ", englishName: "Al-Ghashiyah", englishNameTranslation: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan", aliases: ["Ghashiyah"] },
    { number: 89, name: "سُورَةُ الْفَجْرِ", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan", aliases: ["Fajr"] },
    { number: 90, name: "سُورَةُ الْبَلَدِ", englishName: "Al-Balad", englishNameTranslation: "The City", numberOfAyahs: 20, revelationType: "Meccan", aliases: ["Balad"] },
    { number: 91, name: "سُورَةُ الشَّمْسِ", englishName: "Ash-Shams", englishNameTranslation: "The Sun", numberOfAyahs: 15, revelationType: "Meccan", aliases: ["Shams"] },
    { number: 92, name: "سُورَةُ اللَّيْلِ", englishName: "Al-Layl", englishNameTranslation: "The Night", numberOfAyahs: 21, revelationType: "Meccan", aliases: ["Layl"] },
    { number: 93, name: "سُورَةُ الضُّحَىٰ", englishName: "Ad-Duhaa", englishNameTranslation: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan", aliases: ["Duha"] },
    { number: 94, name: "سُورَةُ الشَّرْحِ", englishName: "Ash-Sharh", englishNameTranslation: "The Relief", numberOfAyahs: 8, revelationType: "Meccan", aliases: ["Sharh", "Al-Inshirah"] },
    { number: 95, name: "سُورَةُ التِّينِ", englishName: "At-Tin", englishNameTranslation: "The Fig", numberOfAyahs: 8, revelationType: "Meccan", aliases: ["Tin"] },
    { number: 96, name: "سُورَةُ الْعَلَقِ", englishName: "Al-'Alaq", englishNameTranslation: "The Clot", numberOfAyahs: 19, revelationType: "Meccan", aliases: ["Alaq"] },
    { number: 97, name: "سُورَةُ الْقَدْرِ", englishName: "Al-Qadr", englishNameTranslation: "The Power", numberOfAyahs: 5, revelationType: "Meccan", aliases: ["Qadr"] },
    { number: 98, name: "سُورَةُ الْبَيِّنَةِ", englishName: "Al-Bayyinah", englishNameTranslation: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan", aliases: ["Bayyinah"] },
    { number: 99, name: "سُورَةُ الزَّلْزَلَةِ", englishName: "Az-Zalzalah", englishNameTranslation: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan", aliases: ["Zalzalah"] },
    { number: 100, name: "سُورَةُ الْعَادِيَاتِ", englishName: "Al-'Adiyat", englishNameTranslation: "The Courser", numberOfAyahs: 11, revelationType: "Meccan", aliases: ["Adiyat"] },
    { number: 101, name: "سُورَةُ الْقَارِعَةِ", englishName: "Al-Qari'ah", englishNameTranslation: "The Calamity", numberOfAyahs: 11, revelationType: "Meccan", aliases: ["Qariah"] },
    { number: 102, name: "سُورَةُ التَّكَاثُرِ", englishName: "At-Takathur", englishNameTranslation: "The Rivalry in world increase", numberOfAyahs: 8, revelationType: "Meccan", aliases: ["Takathur"] },
    { number: 103, name: "سُورَةُ الْعَصْرِ", englishName: "Al-'Asr", englishNameTranslation: "The Declining Day", numberOfAyahs: 3, revelationType: "Meccan", aliases: ["Asr"] },
    { number: 104, name: "سُورَةُ الْهُمَزَةِ", englishName: "Al-Humazah", englishNameTranslation: "The Slanderer", numberOfAyahs: 9, revelationType: "Meccan", aliases: ["Humazah"] },
    { number: 105, name: "سُورَةُ الْفِيلِ", englishName: "Al-Fil", englishNameTranslation: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan", aliases: ["Fil"] },
    { number: 106, name: "سُورَةُ قُرَيْشٍ", englishName: "Quraysh", englishNameTranslation: "Quraysh", numberOfAyahs: 4, revelationType: "Meccan", aliases: [] },
    { number: 107, name: "سُورَةُ الْمَاعُونِ", englishName: "Al-Ma'un", englishNameTranslation: "The Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan", aliases: ["Maun"] },
    { number: 108, name: "سُورَةُ الْكَوْثَرِ", englishName: "Al-Kawthar", englishNameTranslation: "The Abundance", numberOfAyahs: 3, revelationType: "Meccan", aliases: ["Kawthar"] },
    { number: 109, name: "سُورَةُ الْكَافِرُونَ", englishName: "Al-Kafirun", englishNameTranslation: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan", aliases: ["Kafirun"] },
    { number: 110, name: "سُورَةُ النَّصْرِ", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", numberOfAyahs: 3, revelationType: "Medinan", aliases: ["Nasr"] },
    { number: 111, name: "سُورَةُ الْمَسَدِ", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", numberOfAyahs: 5, revelationType: "Meccan", aliases: ["Masad"] },
    { number: 112, name: "سُورَةُ الْإِخْلَاصِ", englishName: "Al-Ikhlas", englishNameTranslation: "The Sincerity", numberOfAyahs: 4, revelationType: "Meccan", aliases: ["Ikhlas"] },
    { number: 113, name: "سُورَةُ الْفَلَقِ", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan", aliases: ["Falaq"] },
    { number: 114, name: "سُورَةُ النَّاسِ", englishName: "An-Nas", englishNameTranslation: "Mankind", numberOfAyahs: 6, revelationType: "Meccan", aliases: ["Nas"] }
];
